channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.2.1
- pip:
  - mlflow==2.21.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
name: mlflow-env
